name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  codeql-sast:
    name: CodeQL SAST scan
    uses: ./.github/workflows/codeql-analysis.yml
    permissions:
      security-events: write
  dependency-review:
    name: Dependency Review scan
    uses: alphagov/govuk-infrastructure/.github/workflows/dependency-review.yml@main
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Always true
        run: echo "runs"